# automatically generated by the FlatBuffers compiler, do not modify
from ctypes import (
    c_int8 as int8,
    c_int8 as int8,
    c_int32 as int32,
)
from pydantic.dataclasses import dataclass
from typing import Protocol


@dataclass
class foo:
    a: bool
    b: bool
    c: int8
    d: int8
    e: int
    f: int32
